### ISSUE TITLE
Unable to connect to any of the specified MySQL hosts.

### ISSUE THREAD

**Issue by yuangang19880212** [PomeloFoundation/Pomelo.EntityFrameworkCore.MyCat#3]
![62](https://cloud.githubusercontent.com/assets/19831723/18025742/cc85b3c2-6c65-11e6-8d63-c2bf0e2ccb73.png)

运行的时候出现：

![63](https://cloud.githubusercontent.com/assets/19831723/18025758/f5106742-6c65-11e6-8ebe-522e9ecee4a1.png)

首先，我认为是我的数据库连接有问题，于是我尝试使用 Pomelo.EntityFrameworkCore.MySql ， optionsBuilder.UseMySQL("server=localhost;database=db_wkmvc;uid=root;pwd=Yuan19880212");
只连接一个主数据库（db_wkmvc），数据插入正常：
![64](https://cloud.githubusercontent.com/assets/19831723/18025770/735c6dee-6c66-11e6-8b6b-23a5b321b008.png)

这说明数据库连接是没问题的，又再次尝试 `optionsBuilder
                .UseMyCat("server=localhost;database=db_wkmvc;uid=root;pwd=Yuan19880212")
                .UseDataNode("localhost", "db_wkmvc_1", "root", "Yuan19880212")
                .UseDataNode("localhost", "db_wkmvc_2", "root", "Yuan19880212");`

使用Migration 数据迁移，奇怪的事情发生了，主数据库(db_wkmvc)并没有成功，但是从库（db_wkmvc1,db_wkmvc2）都增加新表成功：
![65](https://cloud.githubusercontent.com/assets/19831723/18025786/ebbc75a4-6c66-11e6-83c2-8c0193908b73.png)

**Comment by yukozh** [comment]
Are you sure the ef core proxy for mycat is running while you applying the migrations?

**Comment by yuangang19880212** [comment]
@Kagamine 
![66](https://cloud.githubusercontent.com/assets/19831723/18025810/97624b36-6c67-11e6-881c-9ad7a0485897.png)
 不知道这是不是表示成功

**Comment by yukozh** [comment]
Check your mycat uid and pwd is correct or not.

**Comment by yuangang19880212** [comment]
@Kagamine  
你指的是UseMyCat()中 mysql 的 uid和pwd吗，这个应该没问题，
很有可能是mycat服务的问题，windows上安装的可能有问题，我去服务器上试一下。thks

**Comment by yukozh** [comment]
win下尝试以管理员身份运行cmd再运行代理

**Comment by yuangang19880212** [comment]
@Kagamine  我在centos上安装了 mycat：
![e1](https://cloud.githubusercontent.com/assets/19831723/18044502/cee4b04a-6e00-11e6-9bef-8197e995d960.png)
![e2](https://cloud.githubusercontent.com/assets/19831723/18044509/d3c74a96-6e00-11e6-8784-9fc50ce645a5.png)

使用UseMycat ：
![e3](https://cloud.githubusercontent.com/assets/19831723/18044552/faff5428-6e00-11e6-8584-361dee207c66.png)
![e4](https://cloud.githubusercontent.com/assets/19831723/18044554/ff695d6a-6e00-11e6-92d5-3056c923b3ea.png)

总是操作超时
![e5](https://cloud.githubusercontent.com/assets/19831723/18044611/4a0ee010-6e01-11e6-9bc4-2e03b739296a.png)

我尝试使用 EntityFrameworkCore.MySql 数据库创建成功:

![e8](https://cloud.githubusercontent.com/assets/19831723/18045542/e0ea28f6-6e05-11e6-875e-d3beb67d8652.png)

在web中，同样尝试使用 EntityFrameworkCore.MySql  也是没有问题的：
![e6](https://cloud.githubusercontent.com/assets/19831723/18044661/849af5ac-6e01-11e6-9e4f-80a0fa2ed467.png)

而 使用 UseMyCat 也是 操作超时：
![e7](https://cloud.githubusercontent.com/assets/19831723/18044677/91ecd02c-6e01-11e6-800d-a70423373d91.png)

**Comment by yukozh** [comment]
UseMySql你字符串要加Port=8066才是连mycat

**Comment by yukozh** [comment]
MySQL for ef根本没法连mycat

**Comment by yuangang19880212** [comment]
@Kagamine   我是用UseMyCat  ，由于总是超时，于是我用UseMySQL测试一下 数据库连接是否正常。

**Comment by yukozh** [comment]
你可以尝试用Navicat连接mycat，判断是mycat的问题还是ef的问题

**Comment by yuangang19880212** [comment]
@Kagamine  可以连接
![e9](https://cloud.githubusercontent.com/assets/19831723/18081819/acadb48a-6ece-11e6-80d8-059fc81525b5.png)

**Comment by yukozh** [comment]
你要实际具体打开某个数据库的某张表才行，这个步骤不足以说明能够连接

**Comment by yuangang19880212** [comment]
@Kagamine 
![e10](https://cloud.githubusercontent.com/assets/19831723/18081970/500fd09a-6ecf-11e6-8aa8-0f768e8e0322.png)

**Comment by yukozh** [comment]
MyCat的EF代理没有正确运行，TESTDB是不存在的，代理没能成功修改schema.xml，所以导致提示连接不上，请检查代理是否有权限访问mycat目录下的所有内容。从你之前的截图看，EF向代理请求，代理返回401，就是登录失败。

**Comment by yuangang19880212** [comment]
@Kagamine 
![e12](https://cloud.githubusercontent.com/assets/19831723/18082070/bd3e6db6-6ecf-11e6-8951-278cd650bdaa.png)
这应该是正常吧

![e13](https://cloud.githubusercontent.com/assets/19831723/18082138/14ee94c8-6ed0-11e6-9268-8b92b8773aa5.png)

之前那个返回401 那是我在windows上的  现在是在centos上了

**Comment by yuangang19880212** [comment]
@Kagamine   我是按照你的视频一步一步来的 搞了好几天 尝试了N个方法，还是这样。

**Comment by yukozh** [comment]
这边无法还原你的错误，我这边亲测添加表、添加列的migrations一点问题都没有。
