### ISSUE TITLE
大佬出个core 2.0版本的吧，太难了

### ISSUE THREAD

**Issue by wangdaguo68** [PomeloFoundation/Pomelo.EntityFrameworkCore.MyCat#6]
### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

### The issue
Describe what is not working as expected.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
Stack trace:
```

### Further technical details

MyCat version: 
MySQL version: 
Operating system: 

Other details about my project setup:

**Comment by yukozh** [comment]
We don't have any plan for update this lib.
